baseURL = 'https://tiukenywil11.github.io/'
languageCode = 'en-us'
title = 'Kenywil Tiu Blog'
theme="hugo-PaperMod-master"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5